apiKey: 20530694-6e1e-4c29-9358-7124d269a0b1

googleBaseUrl: https://www.google.com/finance/quote
baseUrl: https://www.cvs.com/immunizations
apiBaseUrl: api.cvshealth.com
cvsApiKey: rFd64We9AwyvAFzIXsoSp8bYuewNohOZ
clinicIds:
  - CVS_02339
  - CVS_00843
appointmentDates:
  - 2021-05-03
  - 2021-05-04

state: ma

recipients:
  - kyle@toasttab.com
  - pneckowicz@toasttab.com

emailFrom: kyle.areanraines@gmail.com

coins:
  BTC:
    priceThresholdLow: 30000
    priceThresholdHigh: 40000
    oneHrPctThreshold: 5
  DOGE:
    priceThresholdLow: 0.04
    priceThresholdHigh: 0.07
    oneHrPctThreshold: 10

stocks:
  "TOST:NYSE":
    min: 23.00
