apiKey: 20530694-6e1e-4c29-9358-7124d269a0b1

baseUrl: https://www.cvs.com/immunizations
state: fl

recipients:
  - kyle.areanraines@gmail.com

emailFrom: kyle.areanraines@gmail.com

coins:
  DOGE:
    priceThresholdLow: 0.04
    priceThresholdHigh: 0.1
    oneHrPctThreshold: 10
