apiKey: 20530694-6e1e-4c29-9358-7124d269a0b1

baseUrl: https://www.cvs.com/immunizations
apiBaseUrl: api.cvshealth.com
cvsApiKey: rFd64We9AwyvAFzIXsoSp8bYuewNohOZ
clinicIds:
  - CVS_02339
  - CVS_00843
appointmentDates:
  - 2021-05-03
  - 2021-05-04

state: ma

recipients:
  - kyle.areanraines@gmail.com

emailFrom: kyle.areanraines@gmail.com

coins:
  DOGE:
    priceThresholdLow: 0.04
    priceThresholdHigh: 0.1
    oneHrPctThreshold: 10
